# -*- coding: utf-8 -*-
"""Estrutura_conversor_de_pdf_para_json_markdowon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Wuj1c43o3ZPCDqv_WaMlDXNfEbTWybA

#Importar a biblioteca
"""

!pip install docling

from docling.document_converter import DocumentConverter
from pathlib import Path

"""# Pasta onde os PDFs estão (raiz do Colab)"""

pasta_pdf = Path("/content")

"""#Pasta de saída"""

pasta_saida = Path("/content/aula_2")
pasta_saida.mkdir(exist_ok=True)

"""# Encontrar apenas os 3 PDFs da raiz"""

pdfs = [
    pasta_pdf / "bioetica_e_ia (3).pdf",
    pasta_pdf / "escrita_academica_ia (3).pdf",
    pasta_pdf / "twitter_algoritmo (3).pdf",
]

"""# Filtrar só os que realmente existem"""

pdfs = [p for p in pdfs if p.exists()]

print(f"📄 PDFs encontrados: {len(pdfs)}")
for p in pdfs:
    print(f"   ✅ {p.name}")

"""# Criar conversor"""

converter = DocumentConverter()

"""# Converter cada um para Markdown"""

for pdf in pdfs:
    print(f"\n🔄 Convertendo: {pdf.name}...")

    try:
        resultado = converter.convert(str(pdf))
        markdown = resultado.document.export_to_markdown()

        # Nome do arquivo de saída (mesmo nome, extensão .md)
        nome_saida = pasta_saida / f"{pdf.stem}.md"
        nome_saida.write_text(markdown, encoding="utf-8")

        print(f"   ✅ Salvo: aula_2/{nome_saida.name}")

    except Exception as e:
        print(f"   ❌ Erro: {e}")

"""# Verificar resultado"""

print("\n" + "="*50)
print("📊 ARQUIVOS NA PASTA aula_2:")
print("="*50)
for f in pasta_saida.iterdir():
    print(f"   📝 {f.name}")

"""#Converter os mesmos arquivos para JSON

Vantagem
- Estruturado	O computador entende melhor cada parte do documento
- Fácil de buscar	Você pode procurar por campos específicos
- Pronto para IA	Muitos programas de IA lêem JSON facilmente
- Organizado	Guarda metadados, títulos, parágrafos, tabelas separadamente

#Importar as ferramentas
"""

from docling.document_converter import DocumentConverter
from pathlib import Path
import json

"""#Criar a pasta de saída"""

pasta_saida = Path("/content/aula_2")
pasta_saida.mkdir(exist_ok=True)
print(f"✅ Pasta '{pasta_saida}' pronta!")

"""#Encontrar os PDFs"""

pasta_pdf = Path("/content")

"""#Lista os 3 PDFs específicos"""

pdfs = [
    pasta_pdf / "bioetica_e_ia (3).pdf",
    pasta_pdf / "escrita_academica_ia (3).pdf",
    pasta_pdf / "twitter_algoritmo (3).pdf",
]

"""# Filtra só os que existem"""

pdfs = [p for p in pdfs if p.exists()]

print(f"\n📄 PDFs encontrados: {len(pdfs)}")
for p in pdfs:
    print(f"   ✅ {p.name}")

"""#Criar o conversor"""

converter = DocumentConverter()
print("\n⚙️ Conversor pronto!")

"""#Converter cada PDF para JSON"""

for pdf in pdfs:
    print(f"\n🔄 Convertendo para JSON: {pdf.name}...")

    try:
        # Converte o PDF
        resultado = converter.convert(str(pdf))

        # Extrai o documento como dicionário Python
        documento_dict = resultado.document.export_to_dict()

        # Define o nome do arquivo de saída
        nome_saida = pasta_saida / f"{pdf.stem}.json"

        # Salva o dicionário como arquivo JSON
        with open(nome_saida, "w", encoding="utf-8") as arquivo_json:
            json.dump(documento_dict, arquivo_json, ensure_ascii=False, indent=2)

        print(f"   ✅ Salvo como: aula_2/{nome_saida.name}")

    except Exception as e:
        print(f"   ❌ Erro ao converter {pdf.name}: {e}")

"""#Verificar resultado"""

print("\n" + "="*50)
print("📊 ARQUIVOS JSON NA PASTA aula_2:")
print("="*50)

arquivos_json = list(pasta_saida.glob("*.json"))
if len(arquivos_json) == 0:
    print("⚠️ Nenhum arquivo JSON foi gerado.")
else:
    for json_file in arquivos_json:
        tamanho = json_file.stat().st_size
        print(f"   🗂️  {json_file.name} — {tamanho} bytes")
    print(f"\n🎉 {len(arquivos_json)} arquivo(s) JSON gerado(s) com sucesso!")

"""#Extrair metadados da estrutura do JSON"""

import json
import re
from pathlib import Path

pasta_saida = Path("/content/aula_2")
arquivos_json = sorted([f for f in pasta_saida.glob("*.json") if "_metadados" not in f.name])

resultados = []

for json_file in arquivos_json:
    with open(json_file, "r", encoding="utf-8") as f:
        dados = json.load(f)

    # Junta todos os itens da lista "texts" (que é a estrutura comum dos seus JSONs)
    itens = dados.get("texts", [])

    # ------------------------------------------------------------
    # 1) TÍTULO: Primeiro [section_header] com mais de 10 caracteres
    # ------------------------------------------------------------
    titulo = "Não identificado"
    for item in itens:
        if item.get("label") == "section_header":
            candidato = item.get("text", "").strip()
            if len(candidato) > 10:
                titulo = candidato
                break

    # ------------------------------------------------------------
    # 2) AUTORES: Linha logo após o título ou que contenha "1,"
    # ------------------------------------------------------------
    autores = []
    modo_captura = False
    for item in itens:
        texto = item.get("text", "").strip()
        label = item.get("label", "")

        # Ativa a captura quando encontra o título
        if label == "section_header" and len(texto) > 10:
            modo_captura = True
            continue

        if modo_captura and label == "text":
            # Se parece nome de autor (tem número 1, 2... ou asterisco)
            if re.search(r"\b[A-ZÀ-Ú][a-zà-ú]+.*\b\d\b", texto) or "*" in texto:
                # Limpa números e asteriscos
                nomes_limpos = re.sub(r"[*\d]", "", texto).strip()
                # Se tiver vários autores separados por espaço grande ou tab
                for nome in re.split(r"\s{2,}|(?<=[a-z])\s+(?=[A-ZÀ-Ú])", nomes_limpos):
                    nome = nome.strip().rstrip(",").strip()
                    if len(nome.split()) >= 2 and nome not in autores:
                        autores.append(nome)
                break  # Já pegou a linha de autores
            # Se não tem número mas parece nome próprio (2+ palavras com maiúsculas)
            elif re.match(r"^[A-ZÀ-Ú][a-zà-ú]+ [A-ZÀ-Ú][a-zà-ú]+", texto) and len(texto.split()) >= 2:
                # Garante que não é resumo/palavra-chave
                if not any(p in texto.lower() for p in ["resumo", "abstract", "palavra", "keyword"]):
                    autores.append(texto)
                    break

    # ------------------------------------------------------------
    # 3) ANO: Procura "2025", "2026", etc. nos page_headers ou datas
    # ------------------------------------------------------------
    ano = "Não identificado"
    for item in itens:
        texto = item.get("text", "").strip() + " " + item.get("label", "")
        # Busca ano em contextos de publicação
        match = re.search(r"(?:vol\.?\s*\d+\s*\w*\s*|publicado em |Aceito em |aprovado em )(\d{4})", texto, re.IGNORECASE)
        if match:
            ano = match.group(1)
            break
    if ano == "Não identificado":
        # Plano B: qualquer ano entre 2020-2026 nos primeiros textos
        for item in itens[:10]:
            texto = item.get("text", "")
            match = re.search(r"\b(20[2-9]\d|2030)\b", texto)
            if match:
                ano = match.group(1)
                break

    # ------------------------------------------------------------
    # 4) Monta e salva o resultado
    # ------------------------------------------------------------
    resultado = {
        "arquivo_original": json_file.name.replace(".json", ".pdf"),
        "titulo": titulo,
        "autores": autores if autores else ["Não identificado"],
        "ano_edicao": int(ano) if ano.isdigit() else ano
    }
    resultados.append(resultado)

    nome_saida = pasta_saida / f"{json_file.stem}_metadados.json"
    with open(nome_saida, "w", encoding="utf-8") as f:
        json.dump(resultado, f, ensure_ascii=False, indent=2)

    print(f"✅ {json_file.name}")
    print(f"   Título: {titulo}")
    print(f"   Autores: {autores}")
    print(f"   Ano: {ano}\n")

# Salva resumo geral
resumo_path = pasta_saida / "metadados_aula_2.json"
with open(resumo_path, "w", encoding="utf-8") as f:
    json.dump(resultados, f, ensure_ascii=False, indent=2)

print(f"🎉 Resumo geral salvo em: aula_2/{resumo_path.name}")

from pathlib import Path
import json

# Cria as subpastas
base = Path("/content/aula_2")
(pasta_pdfs := base / "pdfs").mkdir(exist_ok=True)
(pasta_md := base / "markdown").mkdir(exist_ok=True)
(pasta_json := base / "json").mkdir(exist_ok=True)
(pasta_meta := base / "metadados").mkdir(exist_ok=True)

# Move PDFs
for f in base.glob("*.pdf"):
    f.rename(pasta_pdfs / f.name)

# Move Markdowns
for f in base.glob("*.md"):
    f.rename(pasta_md / f.name)

# Move JSONs completos (sem "_metadados")
for f in base.glob("*.json"):
    if "_metadados" not in f.name:
        f.rename(pasta_json / f.name)

# Move metadados
for f in base.glob("*.json"):
    if "_metadados" in f.name:
        f.rename(pasta_meta / f.name)

# Move o resumo geral também
geral = base / "metadados_aula_2.json"
if geral.exists():
    geral.rename(pasta_meta / geral.name)

print("✅ Pastas organizadas!")
print(f"   pdfs/      → {len(list(pasta_pdfs.glob('*')))} arquivos")
print(f"   markdown/  → {len(list(pasta_md.glob('*')))} arquivos")
print(f"   json/      → {len(list(pasta_json.glob('*')))} arquivos")
print(f"   metadados/ → {len(list(pasta_meta.glob('*')))} arquivos")

"""#Baixando a pasta inteira"""

import shutil
from google.colab import files

# Cria o arquivo ZIP
shutil.make_archive("/content/aula_2", "zip", "/content/aula_2")

# Inicia o download no seu computador
files.download("/content/aula_2.zip")

print("\n📥 Download iniciado! O arquivo vai para a pasta 'Downloads' do seu computador.")